#!/bin/bash
# a live-build config for building a test live USB for Rachel's MacbookPro

lb config noauto -b usb-hdd \
    -d squeeze \
    -p xfce basic firmware \
    --archive-areas "main contrib non-free" \
    --mirror-binary http://debian.uchicago.edu/debian \
    --mirror-binary-security http://debian.uchicago.edu/debian-security \
    --tasks "laptop" \
    --hostname "lincolnix-live" \
    --iso-preparer "Grant Centauri" \
    --iso-publisher "Lincolnix Users Collective" \
    --iso-volume "Rache-live" \
    --username "rachel" \
    --packages "rosegarden vmpk qsynth fluidsynth unrar-nonfree squeeze leafpad openoffice.org rhythmbox" \
    "${@}"
