#!/bin/bash
# a minimal console focused live build

lb config noauto \
    -d squeeze \
    -p standard-X11 \
    --archive-areas "main contrib non-free" \
    --mirror-binary http://debian.uchicago.edu/debian \
    --mirror-binary-security http://debian.uchicago.edu/debian-security \
    --bootappend-live "persistent" \ 
    --tasks "laptop" \
    --hostname "lincolnix" \
    --iso-preparer "Grant Centauri" \
    --iso-publisher "Lincolnix Users Collective: info@lincolnix.net" \
    --iso-volume "Lincolnix Mini" \
    --username "user" \
    --packages "" \
    "${@}"
