#!/bin/bash
lb config noauto \
    -d squeeze -p xfce --archive-areas "main contrib non-free" \
    --debian-installer live --mirror-binary http://debian.uchicago.edu/debian \
    --mirror-binary-security http://debian.uchicago.edu/debian-security \
    --tasks "laptop" \
    --packages "openssh-server iceweasel gimp inkscape mtpaint abiword \
                epdfview ntpdate firmware-b43-installer vlc zim xchat \
                wpasupplicant wicd pianobar audacity flashplugin-nonfree \
                calcoo gpicview xfce4-goodies geomview geda alsa-firmware-loaders\
                ace-of-penguins synaptic moc xboard phalanx qgo gnugo less
                wodim w3m rednotebook linux-wlan-ng atmel-firmware firmware-atheros \
                firmware-brcm80211 firmware-ralink firmware-realtek \
                libertas-firmware zd1211-firmware" \
    "${@}"

